CREATE TABLE events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_type VARCHAR(10) NOT NULL,
    operation VARCHAR(10) NOT NULL,
    entity_id BIGINT NOT NULL,
    timestamp BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

ALTER TABLE events ADD CONSTRAINT chk_event_type CHECK (event_type IN ('LIKE', 'REVIEW', 'FRIEND'));
ALTER TABLE events ADD CONSTRAINT chk_operation CHECK (operation IN ('REMOVE', 'ADD', 'UPDATE'));

CREATE INDEX idx_events_user_id ON events(user_id);
CREATE INDEX idx_events_timestamp ON events(timestamp DESC);